package com.ruprocon.jsfapp.modelo;
// Generated 02-sep-2015 2:09:05 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name="factura") 
public class Factura implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
    @Column(name = "idFactura")
    @GeneratedValue(strategy = GenerationType.AUTO)
	private Integer idFactura;
	
	private Usuario usuario;
	private Date fecha;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Factura() {
	}

	public Factura(Usuario usuario, Date fecha) {
		this.usuario = usuario;
		this.fecha = fecha;
	}

	public Factura(Usuario usuario, Date fecha, Set<Pedido> pedidos) {
		this.usuario = usuario;
		this.fecha = fecha;
		this.pedidos = pedidos;
	}

	public Integer getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(Integer idFactura) {
		this.idFactura = idFactura;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

	@Override
	public String toString() {
		return "Factura [idFactura=" + idFactura + ", usuario=" + usuario + ", fecha=" + fecha + ", pedidos=" + pedidos
				+ "]";
	}

}
