package com.ruprocon.jsfapp.modelo;
// Generated 02-sep-2015 2:09:05 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido") 
public class Pedido implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Id
    @Column(name = "idPedido")
    @GeneratedValue(strategy = GenerationType.AUTO)
	private Integer idPedido;
	
	private Factura factura;
	private Producto producto;
	private int cantidad;
	private float precio;

	public Pedido() {
	}

	public Pedido(Factura factura, Producto producto, int cantidad, float precio) {
		this.factura = factura;
		this.producto = producto;
		this.cantidad = cantidad;
		this.precio = precio;
	}

	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public float getPrecio() {
		return this.precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
	}

	@Override
	public String toString() {
		return "Pedido [idPedido=" + idPedido + ", factura=" + factura + ", producto=" + producto + ", cantidad="
				+ cantidad + ", precio=" + precio + "]";
	}

}
